model_name: 'geopacha_object_detection'
experiment_name: 'dinov2_vitl14_test_validclip'

hardware_config: 
    gpu_id: '0'

imagery_data: '/mnt/sarl_commons06/Wernke_projects/GeoPACHA/Imagery_Machine_Learning/Analysis_Images'
#Vector data must be in geojson format.
vector_data:
  #Each AOI should correspond to a single image and have attributes:
  #imageid (with the image id) and 
  #filepath (with the path to the image starting from the image_data directory)
  aois:
    training_aoi_dir: '/home/VANDERBILT/zimmejr1/Documents/GitHub/geopacha_object_detection/OD3/AOI_Training'
    validation_aoi_dir: '/home/VANDERBILT/zimmejr1/Documents/GitHub/geopacha_object_detection/OD3/AOI_Validation'
  label_dir: '/home/VANDERBILT/zimmejr1/Documents/GitHub/geopacha_object_detection/OD3/Labels'

data_config:
  chip_config:
    patch_dim: 896
    upsample_factor: 2
    channel_order: [0,1,2,3,4,5,6,7]
  class_config:
    class_names:
      - 'Corral-Arch'
      - 'Struct-Unroofed-Arch'
      - 'Corral-Mod'
      - 'background'
    class_colors:
      - blue
      - green
      - red
      - black
    null_class: 'background'
  data_loader_config:
    batch_size: 64
    num_workers: 16

model_config:
  model_setup:
    repo_path: "/home/VANDERBILT/zimmejr1/Documents/GitHub/dinov2"
    weights_path: '/home/VANDERBILT/zimmejr1/GeoPACHA/7.pt'
    model_backbone_name: 'dinov2_vitl14'
    lightning_checkpoint_path:
  hyperparameters:
    learning_rate: 4.0e-4
    early_stop_patience: 20
    label_config:
      smoothing: 0.01
      gamma: 2
  

output_config:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  

